---
swagger: "2.0"
info:
  description: "This is a products microservice"
  version: "1.0.0"
  title: "Products microservice"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /products:
    post:
      tags:
      - "products"
      summary: "Add a new product to the ecommerce store"
      description: ""
      operationId: "add_product"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Product object that needs to be added to the class"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.products_controller"
definitions:
  Product:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Sun Glasses"
      status:
        type: "string"
        description: "Product status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Pet"
    example:
      name: "Sun Glasses"
      id: 0
      status: "available"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
